### ISSUE TITLE
View transaction history

### ISSUE THREAD

**Issue by jgs1038** [jgs1038/GESPRO_Practica_2_Curso_2024_2025#27]

**Comment by jgs1038** [comment]
¿Debería mostrar toda la información por pantalla, o mejor deberíamos optar por una vista detallada de los datos?

**Comment by blg1006** [comment]
Quizás una vista en tabla sería lo más apropiado

**Comment by lbr1014** [comment]
No creo que una tabla sea adecuada debido al tamaño de las pantallas con las que trabajaremos.
